version: "2"

services:
  postgres:
    container_name: poc-batch.postgres
    image: postgres:11.4
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - "5432:5432"